version: "3"

services:
    clickhouse-server:
        image: clickhouse/clickhouse-server
        ports:
            - 59000:9000
            - 58123:8123
        ulimits:
            nofile:
                soft: 262144
                hard: 262144
